services:
  backend:
    build:
      context: .
      dockerfile: dockerfile
    image: backend
    container_name: backend
    ports:
      - "4000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=development
      - MONGO_URI=mongodb://root:password@mongodb:27017/docker-Saree?authSource=admin      
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
      - mongodb
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis-saree
    ports:
      - "6379:6379"
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - app-network

networks:
  app-network:
    driver: bridge